### ISSUE TITLE
Lack of unicode handling

### ISSUE THREAD

**Issue by MagerValp** [munkireport/munki_facts#2]
munki_facts crashes when it encounters a unicode value:

``` scripts # ./munki_facts.py 
'x86_64_capable' <type 'str'> True <type 'bool'>
'ipv6_address' <type 'str'> [] <type 'list'>
'machine_type' <type 'str'> 'laptop' <type 'str'>
'munki_version' <type 'str'> '4.1.4.3949' <type 'str'>
'machine_model' <type 'str'> 'MacBookPro15,1' <type 'str'>
'os_vers_major' <type 'str'> 10 <type 'int'>
'os_vers_minor' <type 'str'> 15 <type 'int'>
'os_vers' <type 'str'> '10.15.3' <type 'str'>
'os_build_last_component' <type 'str'> 76 <type 'int'>
'deploy_percent' <type 'str'> 1 <type 'int'>
'catalogs' <type 'str'> ['testing', 'gda'] <type 'list'>
'ipv4_address' <type 'str'> ['192.168.0.120'] <type 'list'>
'os_build_number' <type 'str'> '19D76' <type 'str'>
'date' <type 'str'> datetime.datetime(2020, 5, 18, 16, 14, 27) <type 'datetime.datetime'>
'arch' <type 'str'> 'x86_64' <type 'str'>
'language' <type 'str'> 'sv' <type 'str'>
'ibridge_model_name' <type 'str'> u'Apple T2-s\xe4kerhetskrets' <type 'unicode'>
Traceback (most recent call last):
  File "./munki_facts.py", line 71, in <module>
    main()
  File "./munki_facts.py", line 64, in main
    facts_report = gather_facts(managed_install_report)
  File "./munki_facts.py", line 41, in gather_facts
    facts[key] = str(value)[:65535]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 10: ordinal not in range(128)```

**Comment by tuxudo** [comment]
Can you see if PR #3 fixes this problem?

**Comment by MagerValp** [comment]
That is a dirty, dirty hack but yes, it works :)

**Comment by tuxudo** [comment]
I think it's the best Python 2 can do without getting too crazy, would love to be wrong about that. Most of the other modules use that same dirty hack. Hopefully it'll be a thing of the past when MunkiReport moves to Python 3 :D

**Comment by MagerValp** [comment]
Well not casting unicode strings with `str()` avoids the problem. plistlib and json can handle unicode strings.
